### ISSUE TITLE
Use of undefined constant SIGQUIT if pcntl is not installed

### ISSUE THREAD

**Issue by emurano** [marcelog/Ding#121]
PHP Fatal error:  Undefined constant 'SIGQUIT' in marcelog/ding/src/mg/Ding/Container/Impl/ContainerImpl.php:1074

Looking at that code it appears that if the code is running on Windows then Ding does not set any equivalent to signal handling.

I think Ding should check for PCNTL before trying to execute the this code. That way those of use who don't have it enabled (and can't) won't need to install it.

**Comment by emurano** [comment]
Sorry I should say this is on OSX/MAMP without pcntl enabled.

**Comment by marcelog** [comment]
Hi @emurano!

Could you check if the change in [d88c2f41104440e60b4bcd7d7893de340fc77c27] works for you? I'd also be interested in any comments from @jaehoo who made the original patch in [87c6f4673dc1c787594b7e58e885cc232312e32e].

Cheers,

**Comment by emurano** [comment]
Hi @marcelog,

I'll have a closer look to see where pcntl functions are used and I'll put the function_exists calls.

-Eric

**Comment by emurano** [comment]
Hi @marcelog,

Change d88c2f4 would do nicely!

-Eric

**Comment by marcelog** [comment]
Thank you @emurano, I just merged the change.

Cheers,

**Comment by emurano** [comment]
Thank you kindly!
